services:
  # Database
  tenant-db:
    image: postgres:15-alpine
    container_name: tenant-db
    environment:
      POSTGRES_DB: tenant_db
      POSTGRES_USER: tenant_user
      POSTGRES_PASSWORD: tenant_password
    volumes:
      - tenant_db_data:/var/lib/postgresql/data
    networks:
      - saas-network
    ports:
      - "5433:5432"

  # Backend API
  tenant-api:
    build:
      context: ./tenant-app
      dockerfile: Dockerfile
    container_name: tenant-api
    restart: unless-stopped
    depends_on:
      - tenant-db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: tenant-db
      DB_PORT: 5432
      DB_DATABASE: tenant_db
      DB_USERNAME: tenant_user
      DB_PASSWORD: tenant_password
      APP_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:4200
      LICENSE_PROVIDER_URL: http://provider-api:8000/api
      LICENSE_KEY: SAAS-SZNE-53LV-HOFY-WPPJ
    networks:
      - saas-network
    ports:
      - "8000:8000"

  # Frontend Store
  tenant-store:
    build:
      context: ./tenant-frontend
      dockerfile: Dockerfile
    container_name: tenant-store
    restart: unless-stopped
    depends_on:
      - tenant-api
    ports:
      - "4200:80"
    networks:
      - saas-network

networks:
  saas-network:
    external: true
    name: saas-network

volumes:
  tenant_db_data:
